### ISSUE TITLE
 small misprint in /examples/configuration/configuration.ino

### ISSUE THREAD

**Issue by lejibxl** [ConnorKirkpatrick/E220Lib#2]
**line 30 >** there is no semicolon at the end
**line 22  >** //E220 radioModule(receiver, m0, m1, aux);  
needs to be understood
    Stream &mySerial3 = (Stream &)receiver;
    E220 radioModule(&mySerial3, m0, m1, aux);

ConnorKirkpatrick a big thank you for your work

**Comment by ConnorKirkpatrick** [comment]
Thanks for the comments, it should all be fixed now.
Many thanks for using the lib and I hope it makes your life easier!
If you need any further help with the code please let me know
