### ISSUE TITLE
Example issue Compilation error: 'mySerial' was not declared in this scope

### ISSUE THREAD

**Issue by torphexi** [ConnorKirkpatrick/E220Lib#3]
Hello, first of all thanks for your work.
I am currently trying to get communication between two E220 working and seem to be struggeling a bit. In your examples mySerial is used in the loop however it is out of scope for me. 

Also as a sidenote is there any known issues working with softwareserial as i am really struggeling to get messages to send/recieve.

Thanks for your help!

**Comment by ConnorKirkpatrick** [comment]
Hi there, sorry for the late response.
Would you be able to tell me which file the error is occurring in, Or possibly show me your code?
I've had a quick look through the examples and they should be fine in the release 1.1.2
A possible error I think you may be running into is my use of Serial3, unique to Due and Mega board, if so you need to use the commented-out software serial coded instead.
If you can provide me some more info we should be able to solve this pretty easily

**Comment by ConnorKirkpatrick** [comment]
Closed due to lack of information
