### ISSUE TITLE
E220::printBoardParameters() does not display RSSI Ambient Noise parameter correctly

### ISSUE THREAD

**Issue by mnigbor** [ConnorKirkpatrick/E220Lib#6]
E220::printBoardParameters() does not display the RSSI Ambient Noise parameter properly. It shows "Disabled" regardless of the actual setting. 

Changing the switch statement on line 880 to "switch (_RSSIAmbientNoise)" from "switch (_subPacketSize)"  fixed the issue for me.

**Comment by ConnorKirkpatrick** [comment]
Thanks for the catch! Fixed with v1.3.4
