### ISSUE TITLE
Get Adrees of incoming message

### ISSUE THREAD

**Issue by LucasSchneiderRS** [ConnorKirkpatrick/E220Lib#7]
How do I get the adress of a incoming message in fixed mode?

**Comment by ConnorKirkpatrick** [comment]
When in fixed mode you are broadcasting to any recievers on the correct channel and address. This can still be multiple devices. If you do not include any information in your broadcast about your own address, the recievers will not be able to tell where the message originated. 

In your case you may wish to pre-fix the message data with the senders channel and address to obtain the senders address.
